### ISSUE TITLE
Let's make this repo an 'continuous integration' so that when we accept a Pull request it gets pushed out to the TrueBlocks website

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueBlocks-api#17]

**Comment by wildmolasses** [comment]
I believe you want an easy deployment strategy. Right now the process is a simple manual one: run the deploy.sh script in `./` when you want to publish. However, change the username in the script to jrush@tokenomics.io. My reasoning on a manual deployment process is that there will be times when in fact we don't want the API to update just yet (say during the middle of a batch update).

**Comment by wildmolasses** [comment]
Continuous integration is something else -- a strategy of coordinating between a large team of developers, running tests automatically, automating the build, etc.

**Comment by tjayrush** [comment]
All good. I'm learning. The idea is that we become somewhat more professional in the way we do this because at some point we have to show EF some progress.
