### ISSUE TITLE
The database file needs to be stored on the same location as all other QB caches

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueBlocks-api#19]
We are going to have to require the end user to have a larger SSD drive. This has to be configurable like all other QB tools. The API code can live wherever the user wants it to, but the database be able to be put on an external SSD hard drive. By default this location is ~/.quickBlocks/cache/addr_index, but in the file ~/.quickBlocks/quickBlocks.toml is an entry of where the root of the cache should be.

**Comment by tjayrush** [comment]
In the two files ./api/createdb.js and ./api/server.js make the location of the database.sqllite file be configurable. Maybe from an environment varialbe or from a .env file that doesn't get stored to the repo

**Comment by wildmolasses** [comment]
Seems like you see where to configure the database location parameter. Let me know if you need something else here.

**Comment by tjayrush** [comment]
I remember you showing me something that used a .env file. Is that the standard way to do these things? Can you add that in?
